sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - hexo-source # build hexo-source branch only
script:
  - npm i --save hexo-renderer-ejs hexo-generator-archive hexo-generator-category-enhance hexo-generator-feed hexo-generator-index hexo-generator-tag
  - hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  target-branch: master
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: hexo-source
  local-dir: public
# Handle git submodules yourself
git:
    submodules: false
# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
  # 9fde39a88888f9a80553a1cdab9feb750e0a5b1b
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive